Use pointer to buffer returned by grub_malloc, which is supposed to be suitably aligned for any data type, for holding the UTF16 string converted to host by order from packed struct member catkey->name. The aligned buffer is later used as argument to grub_utf16_to_utf8.
By using a new copy of buffer rather than catkey->name itself for
holding the endianess converted data, we can also get rid of the hunk
restoring byte order of catkey->name to what it was previously.

The solved gcc9 error like this.

[   59s] ../grub-core/fs/hfsplus.c: In function 'list_nodes':
[   59s] ../grub-core/fs/hfsplus.c:738:57: error: taking address of
packed
member of 'struct grub_hfsplus_catkey' may result in an unaligned
pointer value
[-Werror=address-of-packed-member]
[   59s]   738 |   *grub_utf16_to_utf8 ((grub_uint8_t *) filename,
catkey->name,
[   59s]       |
~~~~~~^~~~~~
[   59s] ../grub-core/fs/hfsplus.c: In function 'grub_hfsplus_label':
[   59s] ../grub-core/fs/hfsplus.c:1019:57: error: taking address of
packed
member of 'struct grub_hfsplus_catkey' may result in an unaligned
pointer value
[-Werror=address-of-packed-member]
[   59s]  1019 |   *grub_utf16_to_utf8 ((grub_uint8_t *) (*label),
catkey->name,
[   59s]       |
~~~~~~^~~~~~

Signed-off-by: Michael Chang <mch...@suse.com>