Copy the packed member fp->path_name to the buffer path_name returned by grub_malloc, which is supposed to be suitably aligned for any data type and use path_name as argument to grub_utf8_to_utf16. After the function grub_utf8_to_utf16 returns, copy the content of path_name back to fp->path_name.
The solved gcc9 error like this.

[  243s] ../../grub-core/loader/efi/chainloader.c: In function
'copy_file_path':
[  243s] ../../grub-core/loader/efi/chainloader.c:136:32: error: taking
address
of packed member of 'struct grub_efi_file_path_device_path' may result
in an
unaligned pointer value [-Werror=address-of-packed-member]
[  243s]   136 |   size = grub_utf8_to_utf16 (fp->path_name, len *
GRUB_MAX_UTF16_PER_UTF8,
[  243s]       |                              ~~^~~~~~~~~~~
[  243s] ../../grub-core/loader/efi/chainloader.c:138:12: error: taking
address
of packed member of 'struct grub_efi_file_path_device_path' may result
in an
unaligned pointer value [-Werror=address-of-packed-member]
[  243s]   138 |   for (p = fp->path_name; p < fp->path_name + size;
p++)
[  243s]       |            ^~

Signed-off-by: Michael Chang <mch...@suse.com>