Copy the packed member to the buffer returned by grub_malloc, which is supposed to be suitably aligned for any data type, then use it as argument to grub_utf16_to_utf8.
The solved gcc9 error like this.

[  255s] ../../grub-core/kern/efi/efi.c: In function
'grub_efi_get_filename':
[  255s] ../../grub-core/kern/efi/efi.c:410:60: error: taking address of
packed
member of 'struct grub_efi_file_path_device_path' may result in an
unaligned
pointer value [-Werror=address-of-packed-member]
[  255s]   410 |    p = (char *) grub_utf16_to_utf8 ((unsigned char *)
p,
fp->path_name, len);
[  255s]       |
~^~~~~~~~~~~
[  255s] ../../grub-core/kern/efi/efi.c: In function
'grub_efi_print_device_path':
[  255s] ../../grub-core/kern/efi/efi.c:900:33: error: taking address of
packed
member of 'struct grub_efi_file_path_device_path' may result in an
unaligned
pointer value [-Werror=address-of-packed-member]
[  255s]   900 |     *grub_utf16_to_utf8 (buf, fp->path_name,
[  255s]       |                               ~~^~~~~~~~~~~

Signed-off-by: Michael Chang <mch...@suse.com>