Copy the packed member descstrp->str to the buffer strbuf returned by grub_malloc, which is supposed to be suitably aligned for any data type and after we use strbuf as argument to grub_utf16_to_utf8.
The solved gcc9 error like this.

[  229s] ../../grub-core/commands/usbtest.c: In function
'grub_usb_get_string':
[  229s] ../../grub-core/commands/usbtest.c:104:58: error: taking
address of
packed member of 'struct grub_usb_desc_str' may result in an unaligned
pointer
value [-Werror=address-of-packed-member]
[  229s]   104 |   *grub_utf16_to_utf8 ((grub_uint8_t *) *string,
descstrp->str,
[  229s]       |
~~~~~~~~^~~~~

Signed-off-by: Michael Chang <mch...@suse.com>